// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy3yYxmR3q4gzKoaO9fm4JQtswGAFr89A',
    appId: '1:1045598373294:web:0044ab80efd8f3f867743f',
    messagingSenderId: '1045598373294',
    projectId: 'qrcode-6726d',
    authDomain: 'qrcode-6726d.firebaseapp.com',
    storageBucket: 'qrcode-6726d.firebasestorage.app',
    measurementId: 'G-2YQHHMD8Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhOzfHT_RD0TE7mCLWuyvkzPXHYJcKH4',
    appId: '1:1045598373294:android:905b4465f22ca74967743f',
    messagingSenderId: '1045598373294',
    projectId: 'qrcode-6726d',
    storageBucket: 'qrcode-6726d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ECvvFSkBgziaA9HlENVu2AzuRyPtx-I',
    appId: '1:1045598373294:ios:88a88abdac0b948267743f',
    messagingSenderId: '1045598373294',
    projectId: 'qrcode-6726d',
    storageBucket: 'qrcode-6726d.firebasestorage.app',
    iosBundleId: 'com.example.qrcodeLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ECvvFSkBgziaA9HlENVu2AzuRyPtx-I',
    appId: '1:1045598373294:ios:88a88abdac0b948267743f',
    messagingSenderId: '1045598373294',
    projectId: 'qrcode-6726d',
    storageBucket: 'qrcode-6726d.firebasestorage.app',
    iosBundleId: 'com.example.qrcodeLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy3yYxmR3q4gzKoaO9fm4JQtswGAFr89A',
    appId: '1:1045598373294:web:a10c5bb7240a389e67743f',
    messagingSenderId: '1045598373294',
    projectId: 'qrcode-6726d',
    authDomain: 'qrcode-6726d.firebaseapp.com',
    storageBucket: 'qrcode-6726d.firebasestorage.app',
    measurementId: 'G-PC345N33V3',
  );
}
